// JavaScript is included a data file so it can be compiled and inlined at runtime
// Individual files are also generated by `/js.njk`

require("dotenv").config();
const { compileWebpackTargets } = require("../_utils/compile-webpack");

// Add Webpack compilation targets here
const targets = {
  "critical": "src/_assets/scripts/critical.js",
  "additional": "src/_assets/scripts/additional.js",
  // "service-worker": "src/_assets/scripts/service-worker.js",
};

// Create an object with the compiled files from each entry defined in targets
module.exports = compileWebpackTargets(targets);
